<?php
return [
  'cases' => [
    [ 'id' => 1, 'title' => 'Starter Sparks', 'price' => 2.99, 'tag' => 'starter', 'img' => '/assets/images/case-1.svg', 'risk' => 'low',
      'items' => [
        ['name' => 'Coffee x1', 'value' => 1.50],
        ['name' => 'Gym -5%', 'value' => 0.80],
        ['name' => 'Fuel 1%', 'value' => 0.30],
        ['name' => 'Voucher', 'value' => 2.00],
        ['name' => 'Snack', 'value' => 0.70],
        ['name' => 'Water', 'value' => 0.40],
        ['name' => 'Tea', 'value' => 0.90],
        ['name' => 'Cookie', 'value' => 0.60],
        ['name' => 'Candy', 'value' => 0.50],
        ['name' => 'Sticker', 'value' => 0.10],
        ['name' => 'Keychain', 'value' => 0.30],
        ['name' => 'Badge', 'value' => 0.20],
        ['name' => 'Voucher Mini', 'value' => 1.00],
        ['name' => 'Boost x1', 'value' => 0.80],
        ['name' => 'Fuel 2%', 'value' => 0.60],
        ['name' => 'Coffee x2', 'value' => 2.40],
        ['name' => 'Snack Box', 'value' => 1.20],
        ['name' => 'Starter Mystery Token', 'value' => 0.50],
      ]
    ],
    [ 'id' => 2, 'title' => 'Neon Rush', 'price' => 6.49, 'tag' => 'hot', 'img' => '/assets/images/case-2.svg', 'risk' => 'medium',
      'items' => [
        ['name' => 'Drink x2', 'value' => 3.20],
        ['name' => 'Fuel 2%', 'value' => 0.60],
        ['name' => 'Snack Pack', 'value' => 1.10],
        ['name' => 'Energy Bar', 'value' => 1.50],
        ['name' => 'Voucher', 'value' => 2.50],
        ['name' => 'Glow Sticker', 'value' => 0.30],
        ['name' => 'Keycap', 'value' => 0.80],
        ['name' => 'Neon Band', 'value' => 0.90],
        ['name' => 'LED Badge', 'value' => 1.20],
        ['name' => 'Drink x3', 'value' => 4.20],
        ['name' => 'Fuel 3%', 'value' => 1.10],
        ['name' => 'Snack XL', 'value' => 1.80],
        ['name' => 'Voucher+', 'value' => 3.00],
        ['name' => 'VIP Pass', 'value' => 5.00],
        ['name' => 'Neon Charm', 'value' => 0.70],
        ['name' => 'Glow Band', 'value' => 0.60],
        ['name' => 'Neon Pulse Fragment', 'value' => 0.50],
        ['name' => 'Drink x1', 'value' => 1.60],
      ]
    ],
    [ 'id' => 3, 'title' => 'Limited Pulse', 'price' => 12.99, 'tag' => 'limited', 'img' => '/assets/images/case-3.svg', 'risk' => 'high',
      'items' => [
        ['name' => 'Cinema -10%', 'value' => 4.50],
        ['name' => 'Fuel 3%', 'value' => 1.20],
        ['name' => 'Voucher+', 'value' => 3.00],
        ['name' => 'Premium Snack', 'value' => 2.10],
        ['name' => 'Pulse Badge', 'value' => 0.40],
        ['name' => 'Gift Card', 'value' => 5.00],
        ['name' => 'Poster', 'value' => 1.30],
        ['name' => 'Keychain+', 'value' => 0.60],
        ['name' => 'Sticker Pack', 'value' => 0.70],
        ['name' => 'Fuel 4%', 'value' => 1.60],
        ['name' => 'Cinema -5%', 'value' => 2.50],
        ['name' => 'Voucher Pro', 'value' => 4.00],
        ['name' => 'Limited Artifact Shard', 'value' => 0.50],
        ['name' => 'Poster+', 'value' => 1.70],
        ['name' => 'Gift Box', 'value' => 3.30],
        ['name' => 'Pulse Pin', 'value' => 0.80],
        ['name' => 'Cinema Pass', 'value' => 6.00],
        ['name' => 'Fuel 5%', 'value' => 2.10],
      ]
    ],
    [ 'id' => 4, 'title' => 'Daily Boost', 'price' => 3.49, 'tag' => 'starter', 'img' => '/assets/images/case-1.svg', 'risk' => 'low', 'items' => [
      ['name' => 'Coffee x1', 'value' => 1.20], ['name' => 'Snack', 'value' => 0.70], ['name' => 'Water', 'value' => 0.40],
      ['name' => 'Tea', 'value' => 0.80], ['name' => 'Cookie', 'value' => 0.60], ['name' => 'Candy', 'value' => 0.50],
      ['name' => 'Sticker', 'value' => 0.10], ['name' => 'Keychain', 'value' => 0.30], ['name' => 'Badge', 'value' => 0.20],
      ['name' => 'Voucher Mini', 'value' => 1.00], ['name' => 'Boost x1', 'value' => 0.80], ['name' => 'Fuel 2%', 'value' => 0.60],
      ['name' => 'Coffee x2', 'value' => 2.40], ['name' => 'Snack Box', 'value' => 1.20], ['name' => 'Daily Hidden Chip', 'value' => 0.50],
      ['name' => 'Energy Bar', 'value' => 1.10], ['name' => 'Voucher', 'value' => 1.50], ['name' => 'Ticket', 'value' => 0.90],
    ] ],
    [ 'id' => 5, 'title' => 'Violet Vault', 'price' => 24.99, 'tag' => 'limited', 'img' => '/assets/images/case-3.svg', 'risk' => 'very-high', 'items' => [
      ['name' => 'Violet Charm', 'value' => 1.80], ['name' => 'Premium Voucher', 'value' => 6.00], ['name' => 'Fuel 4%', 'value' => 1.60],
      ['name' => 'Poster', 'value' => 1.30], ['name' => 'Keychain+', 'value' => 0.60], ['name' => 'Sticker Pack', 'value' => 0.70],
      ['name' => 'Glow Pin', 'value' => 0.90], ['name' => 'Gift Box', 'value' => 3.30], ['name' => 'VIP Pass', 'value' => 5.00],
      ['name' => 'Neon Band', 'value' => 0.90], ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20],
      ['name' => 'Fuel 5%', 'value' => 2.10], ['name' => 'Voucher Pro', 'value' => 4.00], ['name' => 'Violet Secret Sigil', 'value' => 0.50],
      ['name' => 'Poster+', 'value' => 1.70], ['name' => 'Gift Card', 'value' => 5.50], ['name' => 'Violet Badge', 'value' => 0.80],
    ] ],
    [ 'id' => 6, 'title' => 'Hyper Nova', 'price' => 49.99, 'tag' => 'hot', 'img' => '/assets/images/case-2.svg', 'risk' => 'medium', 'items' => [
      ['name' => 'Nova Sticker', 'value' => 1.10], ['name' => 'Hyper Voucher', 'value' => 7.00], ['name' => 'Fuel 6%', 'value' => 2.60],
      ['name' => 'Energy Drink', 'value' => 2.20], ['name' => 'Neon Charm', 'value' => 0.70], ['name' => 'Glow Band', 'value' => 0.60],
      ['name' => 'Hyper Hidden Core', 'value' => 0.50], ['name' => 'Poster XL', 'value' => 2.10], ['name' => 'Gift Pack', 'value' => 6.30],
      ['name' => 'VIP Nova Pass', 'value' => 8.00], ['name' => 'Badge+', 'value' => 1.60], ['name' => 'Keycap', 'value' => 0.80],
      ['name' => 'Voucher Ultra', 'value' => 9.00], ['name' => 'Fuel 7%', 'value' => 3.10], ['name' => 'Premium Snack', 'value' => 2.10],
      ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20], ['name' => 'Neon Band', 'value' => 0.90],
    ] ],
  ],
  'eventCases' => [
    [ 'id' => 101, 'title' => 'Disco Drop', 'price' => 7.99, 'tag' => 'limited', 'img' => '/assets/images/case-2.svg', 'risk' => 'medium', 'items' => [
      ['name' => 'Glow Band', 'value' => 0.60], ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20],
      ['name' => 'Energy Bar', 'value' => 1.50], ['name' => 'Voucher', 'value' => 2.50], ['name' => 'Glow Sticker', 'value' => 0.30],
      ['name' => 'Keycap', 'value' => 0.80], ['name' => 'Neon Band', 'value' => 0.90], ['name' => 'VIP Pass', 'value' => 5.00],
      ['name' => 'Fuel 3%', 'value' => 1.10], ['name' => 'Snack XL', 'value' => 1.80], ['name' => 'Voucher+', 'value' => 3.00],
      ['name' => 'Gift Box', 'value' => 3.30], ['name' => 'Disco Secret Chip', 'value' => 0.50], ['name' => 'Poster', 'value' => 1.30],
      ['name' => 'Keychain+', 'value' => 0.60], ['name' => 'Sticker Pack', 'value' => 0.70], ['name' => 'Cinema -5%', 'value' => 2.50],
    ] ],
    [ 'id' => 102, 'title' => 'Neon Nights', 'price' => 15.49, 'tag' => 'hot', 'img' => '/assets/images/case-3.svg', 'risk' => 'high', 'items' => [
      ['name' => 'Voucher Pro', 'value' => 4.00], ['name' => 'Neon Nights Relic', 'value' => 0.50], ['name' => 'Poster+', 'value' => 1.70],
      ['name' => 'Gift Card', 'value' => 5.50], ['name' => 'Violet Badge', 'value' => 0.80], ['name' => 'Energy Drink', 'value' => 2.20],
      ['name' => 'Neon Charm', 'value' => 0.70], ['name' => 'Glow Band', 'value' => 0.60], ['name' => 'Poster XL', 'value' => 2.10],
      ['name' => 'Gift Pack', 'value' => 6.30], ['name' => 'VIP Nova Pass', 'value' => 8.00], ['name' => 'Badge+', 'value' => 1.60],
      ['name' => 'Keycap', 'value' => 0.80], ['name' => 'Voucher Ultra', 'value' => 9.00], ['name' => 'Fuel 7%', 'value' => 3.10],
      ['name' => 'Premium Snack', 'value' => 2.10], ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20],
    ] ],
    [ 'id' => 103, 'title' => 'Violet Vault+', 'price' => 29.99, 'tag' => 'limited', 'img' => '/assets/images/case-1.svg', 'risk' => 'very-high', 'items' => [
      ['name' => 'Violet Charm', 'value' => 1.80], ['name' => 'Premium Voucher', 'value' => 6.00], ['name' => 'Fuel 4%', 'value' => 1.60],
      ['name' => 'Poster', 'value' => 1.30], ['name' => 'Keychain+', 'value' => 0.60], ['name' => 'Sticker Pack', 'value' => 0.70],
      ['name' => 'Glow Pin', 'value' => 0.90], ['name' => 'Gift Box', 'value' => 3.30], ['name' => 'VIP Pass', 'value' => 5.00],
      ['name' => 'Neon Band', 'value' => 0.90], ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20],
      ['name' => 'Fuel 5%', 'value' => 2.10], ['name' => 'Voucher Pro', 'value' => 4.00], ['name' => 'Violet Vault Rune', 'value' => 0.50],
      ['name' => 'Poster+', 'value' => 1.70], ['name' => 'Gift Card', 'value' => 5.50], ['name' => 'Violet Badge', 'value' => 0.80],
    ] ],
    [ 'id' => 104, 'title' => 'Daily Boost+', 'price' => 5.49, 'tag' => 'starter', 'img' => '/assets/images/case-1.svg', 'risk' => 'low', 'items' => [
      ['name' => 'Coffee x1', 'value' => 1.20], ['name' => 'Snack', 'value' => 0.70], ['name' => 'Water', 'value' => 0.40],
      ['name' => 'Tea', 'value' => 0.80], ['name' => 'Cookie', 'value' => 0.60], ['name' => 'Candy', 'value' => 0.50],
      ['name' => 'Sticker', 'value' => 0.10], ['name' => 'Keychain', 'value' => 0.30], ['name' => 'Badge', 'value' => 0.20],
      ['name' => 'Voucher Mini', 'value' => 1.00], ['name' => 'Boost x1', 'value' => 0.80], ['name' => 'Fuel 2%', 'value' => 0.60],
      ['name' => 'Coffee x2', 'value' => 2.40], ['name' => 'Snack Box', 'value' => 1.20], ['name' => 'Daily Boost Relic', 'value' => 0.50],
      ['name' => 'Energy Bar', 'value' => 1.10], ['name' => 'Voucher', 'value' => 1.50], ['name' => 'Ticket', 'value' => 0.90],
    ] ],
    [ 'id' => 105, 'title' => 'Hyper Nova X', 'price' => 54.99, 'tag' => 'hot', 'img' => '/assets/images/case-2.svg', 'risk' => 'medium', 'items' => [
      ['name' => 'Nova Sticker', 'value' => 1.10], ['name' => 'Hyper Voucher', 'value' => 7.00], ['name' => 'Fuel 6%', 'value' => 2.60],
      ['name' => 'Energy Drink', 'value' => 2.20], ['name' => 'Neon Charm', 'value' => 0.70], ['name' => 'Glow Band', 'value' => 0.60],
      ['name' => 'Hyper Nova Core', 'value' => 0.50], ['name' => 'Poster XL', 'value' => 2.10], ['name' => 'Gift Pack', 'value' => 6.30],
      ['name' => 'VIP Nova Pass', 'value' => 8.00], ['name' => 'Badge+', 'value' => 1.60], ['name' => 'Keycap', 'value' => 0.80],
      ['name' => 'Voucher Ultra', 'value' => 9.00], ['name' => 'Fuel 7%', 'value' => 3.10], ['name' => 'Premium Snack', 'value' => 2.10],
      ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20], ['name' => 'Neon Band', 'value' => 0.90],
    ] ],
    [ 'id' => 106, 'title' => 'Pulse Deluxe', 'price' => 19.99, 'tag' => 'limited', 'img' => '/assets/images/case-3.svg', 'risk' => 'high', 'items' => [
      ['name' => 'Premium Snack', 'value' => 2.10], ['name' => 'Pulse Badge', 'value' => 0.40], ['name' => 'Gift Card', 'value' => 5.00],
      ['name' => 'Poster', 'value' => 1.30], ['name' => 'Keychain+', 'value' => 0.60], ['name' => 'Sticker Pack', 'value' => 0.70],
      ['name' => 'Fuel 4%', 'value' => 1.60], ['name' => 'Cinema -5%', 'value' => 2.50], ['name' => 'Voucher Pro', 'value' => 4.00],
      ['name' => 'Pulse Deluxe Relic', 'value' => 0.50], ['name' => 'Poster+', 'value' => 1.70], ['name' => 'Gift Box', 'value' => 3.30],
      ['name' => 'Pulse Pin', 'value' => 0.80], ['name' => 'Cinema Pass', 'value' => 6.00], ['name' => 'Fuel 5%', 'value' => 2.10],
      ['name' => 'Glow Band', 'value' => 0.60], ['name' => 'LED Badge', 'value' => 1.20], ['name' => 'Drink x3', 'value' => 4.20],
    ] ],
  ],
];